### ISSUE TITLE
 Minification failed due to Exception error

### ISSUE THREAD

**Issue by ghevge** [logicsquad/minifier#3]
Hi,
I'm trying to minify a .js file which contains 23k+ lines, but I'm getting this error:

net.logicsquad.minifier.MinificationException: Minification failed due to Exception.
        at net.logicsquad.minifier.js.JSMinifier.minify(JSMinifier.java:331)
        at com.kp.mw.maven.MinimizeStaticReources.compileJs(MinimizeStaticReources.java:111)
        at com.kp.mw.maven.MinimizeStaticReources.main(MinimizeStaticReources.java:64)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:279)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: net.logicsquad.minifier.js.JSMinifier$UnterminatedStringLiteralException
        at net.logicsquad.minifier.js.JSMinifier.action(JSMinifier.java:210)
        at net.logicsquad.minifier.js.JSMinifier.minify(JSMinifier.java:324)
        ... 4 more

Nothing else.

My java code looks like this:

```
public static void compileJs(String outputFile, String code) throws IOException, MinificationException {
        Reader input = new StringReader(code);
        Writer output = new FileWriter(outputFile);
        JSMinifier min = new JSMinifier(input);
        try {
            min.minify(output);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```

Any idea what is wrong?
Thanks

I am on JDK 17 
<dependency>
		<groupId>net.logicsquad</groupId>
		<artifactId>minifier</artifactId>
		<version>1.1</version>
</dependency>

**Comment by paulhoadley** [comment]
Minifier thinks there's an _unterminated string literal_ in the input:

```
Caused by: net.logicsquad.minifier.js.JSMinifier$UnterminatedStringLiteralException
```

It certainly would be a nice feature if it told you where it was in the input. Can you attach or otherwise point me at the input file?

**Comment by paulhoadley** [comment]
Unless you can help me reproduce the issue, there's nothing more we can do here.
